php:
  build: .
  container_name: app_crud_orm
  ports:
   - "8889:80"
   - "4443:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db
  
db:
  image: mysql:8.0
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phpcrudluiz
   - MYSQL_DATABASE=phpcrud
